set-option -g default-terminal "xterm-256color"
set-option -a terminal-features 'xterm-256color:RGB'
set-option -sg escape-time 10
set-option -g focus-events on

bind -n M-H previous-window
bind -n M-L next-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'fabioluciano/tmux-tokyo-night'

set-option -g mode-keys vi

# set vi-mode
set -g @plugin 'tmux-plugins/tmux-yank'
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# mouse support
set -g mouse on

set -g @theme_variation 'storm'
set -g @theme_left_separator ''
set -g @theme_right_separator ''
set -g @theme_plugins 'datetime,weather,playerctl,yay'

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

run '~/.tmux/plugins/tpm/tpm'
